### ISSUE TITLE
Get option set values

### ISSUE THREAD

**Issue by shalemperez** [AlexaCRM/dynamics-webapi-toolkit#10]
How can i get "option set" values from a field?

**Comment by georged** [comment]
@shalemperez I'm not sure what the question is. At this point we implement Web API "as is", and optionset values are just integers.

**Comment by shalemperez** [comment]
@georged thanks for the response, what i need to know is how i can get all the options from a select in CRM, example: Gender (Male, female)

**Comment by wizardist** [comment]
You need to use `MetadataRegistry` for that.

```php
$c = new Client( $settings, $middleware );
$client = new \AlexaCRM\WebAPI\Client( $c );
$metadata = new \AlexaCRM\WebAPI\MetadataRegistry( $client );

/**
 * @var \AlexaCRM\Xrm\Metadata\PicklistAttributeMetadata $attribute
 */
$attribute = $metadata->getDefinition( 'new_entity' )->Attributes['new_optionsetattr'];

print_r( $attribute->OptionSet->Options );
```

Bear in mind that `$attribute` may be of `BooleanAttributeMetadata` type or other.

**Comment by shalemperez** [comment]
@wizardist bro! you are the best!! works at first try! :D

**Comment by shalemperez** [comment]
Will be nice to have all those aditionals functions in the documentation.
