### ISSUE TITLE
Deprecated return type for function offsetGet

### ISSUE THREAD

**Issue by sebasparola** [AlexaCRM/dynamics-webapi-toolkit#107]
**Describe the bug**
For newer versions of PHP (>=8.1) the offsetGet functionality is giving deprecation warnings

**To Reproduce**
Create a new Entity
![555](https://github.com/AlexaCRM/dynamics-webapi-toolkit/assets/11440721/d423ef86-baed-4cf5-84d6-e215e122230e)

**Expected behavior**
No warning or Error

**Additional context**
![Screenshot from 2024-04-03 11-11-05](https://github.com/AlexaCRM/dynamics-webapi-toolkit/assets/11440721/aaa70c25-50e0-4fea-a78d-813425f6575a)
![Screenshot from 2024-04-03 11-15-39](https://github.com/AlexaCRM/dynamics-webapi-toolkit/assets/11440721/ad297e20-8612-4466-8de8-f42bc2ccbee4)

**Comment by sebasparola** [comment]
Two possible solutions I have check and works for this is:

1. 
add the return type mixed for the function in the Entity class:
public function offsetGet( $offset ) : mixed {

or 

2. 
add the overrride #[\ReturnTypeWillChange] annotation to the offsetGet function

**Comment by mrudov** [comment]
Fixed in `v4` branch. Please refer README.md for details.
