### ISSUE TITLE
Error with AlexaCRM\Cache\NullCacheItem::get()

### ISSUE THREAD

**Issue by gurunathanrs** [AlexaCRM/dynamics-webapi-toolkit#108]
Declaration of AlexaCRM\Cache\NullCacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed in /vendor/alexacrm/dynamics-webapi-toolkit/src/Cache/NullCacheItem.php on line 69

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by gurunathanrs** [comment]
Hi Team,

Do you have any update on this?

**Comment by mrudov** [comment]
Hello, gurunathanrs.
Could you please provide a bit more information about the issue?
Do you use the latest version of the toolkit (it's 3.3.1 right now)? What version of php do you use? And did you manually install any of the required packages specified in the composer.json, like 'psr/cache'?

**Comment by gurunathanrs** [comment]
1. The issue happened after updated to the latest version. We don't know how to downgrade.
2. PHP version is 8.1.23.
3. We didn't do any manual installation, we use composer.

**Comment by mrudov** [comment]
As a temporal solution try to use a previous stable version 3.2, like so:
`composer require -W 'alexacrm/dynamics-webapi-toolkit:3.2'`

**Comment by sallison117** [comment]
Also just got this issue after updating. Was working fine before I had to do a composer re-install of everything which gave the newest version and I got the same issue. PHP 8.3.3.

**Comment by gurunathanrs** [comment]
Hi mrudov,

I tried to downgrade by using the composer command you said.
But i face conflict with psr/log.
⁠existing version of psr/log  is 3.0.0.
But dynamics-webapi-toolkit 3.2.0 requires psr/log ^1.0 || ^2.0.

How to resolve?

**Comment by mrudov** [comment]
Please try to update to the latest version 3.3.2, it should resolve the issue.
`composer require -W 'alexacrm/dynamics-webapi-toolkit:^3.3.2'`
You can also try to remove the toolkit and reinstall it from scratch.

If the issue is still persist please try to use a development version, but note it's still a work in progress:
`composer require -W 'alexacrm/dynamics-webapi-toolkit:v4.x-dev'`

**Comment by gurunathanrs** [comment]
I downgraded to 3.3.0 and it's working fine.
But the original issue with the latest version still exists. We will check it later.
