### ISSUE TITLE
Metadata request returned a fatal error

### ISSUE THREAD

**Issue by aharonnik** [AlexaCRM/dynamics-webapi-toolkit#11]
I have this simple code: (yo.php)
require_once 'vendor/autoload.php';
$client = \AlexaCRM\WebAPI\ClientFactory::createOnlineClient(
    'https://mysubdomain.crm.dynamics.com',
    'my app ID',
    'my secret code'
	);
$contact = new \AlexaCRM\Xrm\Entity( 'contact' );
$contact['firstname'] = 'Nancy';
$contact['lastname'] = 'Anderson';
$contact['emailaddress1'] = 'someone_c@example.com';

$contactId = $client->Create( $contact );

But I'll get this error:
PHP Fatal error:  Uncaught AlexaCRM\WebAPI\ToolkitException: Metadata request returned a 403 code in .....\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php:121
Stack trace:
#0 ...\yo.php(26): AlexaCRM\WebAPI\Client->Create(Object(AlexaCRM\Xrm\Entity))
#1 {main}
  thrown in ...\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php on line 121

**Comment by georged** [comment]
@aharonnik
403 means unauthorized. Could be one of the few reasons : wrong appid / secret, no API permissions granted to the app, no app user in Dynamics, insufficient user role in Dynamics. 
You need to get logging going to get more information about the error.

**Comment by aharonnik** [comment]
I checked the appid and secret key. There is also api permission granted to
the app. App user has been defined in dynamics. Role to create and write
contract has been given.

How can I get logging?

**Comment by georged** [comment]
It's not sufficient to have a role just to create/write contract (contract?). You also need permissions to read metadata.

createOnlineClient takes array of services including logger and cache. It'll be something like 

`
$client = \AlexaCRM\WebAPI\ClientFactory::createOnlineClient(
'https://mysubdomain.crm.dynamics.com',
'my app ID',
'my secret code',
array ('logger'  => instanceImplementingLoggerInterface)
);
