### ISSUE TITLE
Response 401 UnAuthorise

### ISSUE THREAD

**Issue by Andlibmehndi** [AlexaCRM/dynamics-webapi-toolkit#12]
Hi,
I have connected using the tutorial which mentioned on "dynamics-webapi-toolkit", but there is one error is arriving while executing create/update/delete or retrieve.

the Error is **"Exception has occurred.
GuzzleHttp\Exception\ClientException: Client error: `GET https://organizationURL/api/data/v9.1/` resulted in a `401 Unauthorized` response"**

my code is as below:
 ```
$client = \AlexaCRM\WebAPI\ClientFactory::createOnlineClient(
        'URL',
        'Application ID',
        'App key'
    );
    $contact = new \AlexaCRM\Xrm\Entity( 'contact' );
    $contact['firstname'] = 'Nancy';
    $contact['lastname'] = 'Anderson';
    $contact['emailaddress1'] = 'someone_c@example.com';

    $contactId = $client->Create( $contact );
```

could you please help me with this.

**Comment by georged** [comment]
@Andlibmehndi 

there could be multiple reasons for this error:

- Have you registered the app in Azure AD?
- Have you created an app secret (key)?
- Have you created an app user in Dynamics 365?
- Have you assigned any role to that user?

Thanks

**Comment by Andlibmehndi** [comment]
@georged 
yes, I have done all this thing.

**Comment by georged** [comment]
@Andlibmehndi 

I don't have enough information to advise. You need to attach a logger then and capture the details. Instructions are [here](https://github.com/AlexaCRM/dynamics-webapi-toolkit/wiki/Tutorial#settings)

Thanks

**Comment by Andlibmehndi** [comment]
@georged 
I have prepared one small demo fo this that why I have not added any loggers but when i debugging it I have found that token is null.
is this the token issue?

Thanks.

**Comment by georged** [comment]
That'd be authentication issue. For more details you need to look what's coming back from Azure AD. Perhaps secret is not correct but I cannot really tell.

**Comment by Andlibmehndi** [comment]
@georged  
I have tried with C# code there it is retrieving the data but they are also using Bearer token.

Thanks

**Comment by Andlibmehndi** [comment]
@georged 
Here it's the image which I was getting a response from Azure AD
![temp](https://user-images.githubusercontent.com/31627825/65598025-250b8800-dfb8-11e9-881c-ccb3ed06024d.JPG)

Thanks

**Comment by georged** [comment]
@Andlibmehndi could be various reasons, I can't tell without a log. For example, if a clock on your server is off, you'd get a null token.

**Comment by Andlibmehndi** [comment]
@georged Thanks 
I will try to debug that scenario hope this will work.
