### ISSUE TITLE
 Missing type declarations for Php8.1

### ISSUE THREAD

**Issue by arendicom-astaufenberg** [AlexaCRM/dynamics-webapi-toolkit#127]
**Describe the Bug**
The file src/Cache/NullCacheItem.php has missing type declarations in release 3.3.1 and 3.3.2, which leads to a fatal error in PHP 8.1 when strict types are enabled.

**To Reproduce**
Execute the code in PHP 8.1 with strict types enabled.

**Additional context**
Attached is a copy of NullCacheItem.php with the corrected type declarations. This should resolve the issue.

[NullCacheItem.zip](https://github.com/user-attachments/files/17992496/NullCacheItem.zip)

Please let us know once this issue is resolved, so we can update the code on our system.

**Comment by georged** [comment]
For PHP *.x use v4 branch in composer:

`"alexacrm/dynamics-webapi-toolkit": "dev-v4"` 

Current implementation must stay in place for 7.4 compatibility.

**Comment by arendicom-astaufenberg** [comment]
Thank you, that works well for us
