### ISSUE TITLE
How do i use MetadataCollection in this library

### ISSUE THREAD

**Issue by Andlibmehndi** [AlexaCRM/dynamics-webapi-toolkit#14]
Hi
In your previous library **"php-crm-toolkit"** you have given **MetadataCollection**. 
could you please guide me that how can I used same **MetadataCollection**  functionality in 
**"dynamics-webapi-toolkit"** library? or any other solution to use **MetadataCollection** ?

**Comment by wizardist** [comment]
Hi @Andlibmehndi 

You have `MetadataRegistry` which provides access to your instance metadata. It supports PSR-6 compliant cache libraries. `getDefinition()` method returns EntityMetadata for a single entity. 

Refer to Xrm SDK docs for more info on what's in there: https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata?view=dynamics-general-ce-9

**Comment by Andlibmehndi** [comment]
@wizardist Thanks
