### ISSUE TITLE
How to use phpfastCache in library

### ISSUE THREAD

**Issue by Andlibmehndi** [AlexaCRM/dynamics-webapi-toolkit#15]
Hi, @wizardist 
I am using phpFastCache in my project.
Can you please guide me how to use this in **$settings->cachePool = $cacheAdapter;** ?

**Comment by wizardist** [comment]
Hi @Andlibmehndi 

phpFastCache seems to be PSR-6 compliant out of box, so all you need is assign a phpFastCache pool to `$settings->cachePool`.

HTH
