### ISSUE TITLE
Add versioning/tags to the library?

### ISSUE THREAD

**Issue by reisba** [AlexaCRM/dynamics-webapi-toolkit#17]
Have you considered using some versioning scheme and adding tags to the project? It would make it a lot easier and reliable to use this library if could explicitly depend and install a specific version and not worry about anything breaking from an unintended update.

**Comment by wizardist** [comment]
Hi @reisba 

Yes, as said in readme, the toolkit will be tagged. As for now, I would suggest requiring the specific commit identifier in `composer.json`. That would protect your system from breaking changes. See example here: https://stackoverflow.com/a/25992188/965872

Thanks
