### ISSUE TITLE
Retrieving Display Names for Meta Data of Entities?

### ISSUE THREAD

**Issue by MCKLtech** [AlexaCRM/dynamics-webapi-toolkit#18]
**Is your feature request related to a problem? Please describe.**

Is it possible to retrieve the display names for metadata associated with an entity? For example, Contacts, can the display name of meta be mapped?

**Describe the solution you'd like**

An addition to the tutorial would be perfect.

**Describe alternatives you've considered**

I've reviewed the source code and tried a few queries myself, but I can't seem to retrieve the right records.

**Additional context**

None

**Comment by georged** [comment]
Hi @MCKLtech 

I'm not sure I understand what are you trying to do. What is the "display name of meta"?? Can you provide a use case so that we better understand what are you after

Thanks
George
