### ISSUE TITLE
Rejected access token

### ISSUE THREAD

**Issue by Andlibmehndi** [AlexaCRM/dynamics-webapi-toolkit#19]
Hi @georged ,
 i have add PhpFasteCache lib for caching purpose but one time a day it giving below error 
"Dynamics 365 rejected the access token".
Could you please help me with this?

**Comment by georged** [comment]
Hi @Andlibmehndi 
cache can't possibly give you this error as it's the error returned by Dynamics 365. Usually it implies stale token (perhaps pulled from cache) that is no longer valid.

HTH
