### ISSUE TITLE
Setting lookup fields

### ISSUE THREAD

**Issue by webfaqtory** [AlexaCRM/dynamics-webapi-toolkit#2]
I have the same requirement as an issue for the php-crm-toolkit https://github.com/AlexaCRM/php-crm-toolkit/issues/25

Really need some help on how to implement this. Many thanks

**Comment by georged** [comment]
@webfaqtory the issue 25 has been resolved and the code samples provided. You don't give us any samples of your code and what is not working so I'm not sure what help can we provide.

**Comment by webfaqtory** [comment]
I just needed to know how to achieve the same setting of a lookup value in the dynamics-webapi-toolkit as the example you gave for the php-crm-toolkit. After looking at the toolkit source code I came up with:

`$case['customerid'] = new AlexaCRM\Xrm\EntityReference( 'account', $accountId );`

Which works

**Comment by georged** [comment]
Great, @webfaqtory, spot on, you're on the right track!

**Comment by wizardist** [comment]
@webfaqtory see the [Tutorial page](https://github.com/AlexaCRM/dynamics-webapi-toolkit/wiki/Tutorial#associate-records-on-createupdate) as well.
