### ISSUE TITLE
[Question] Is cachePool unique to the organisation? 

### ISSUE THREAD

**Issue by MCKLtech** [AlexaCRM/dynamics-webapi-toolkit#20]
I'm currently setting up my client as follows in Laravel:

`$services = ['cachePool' => app('cache.psr6')];
        
   $client = \AlexaCRM\WebAPI\ClientFactory::createOnlineClient(
            $meta->meta['organizationURI'],
            $meta->meta['applicationID'],
            $meta->meta['applicationSecret'],
            $services
   );`

As you can see, I'm supplying a PSR6 adapter and the clients are created dynamically from a database of credentials. My question relates to the cache instance and if it is shared?

For example, two separate organisations have clients as set up using the method above. Let's assume they both make a Web API call that this library caches. Is there a possibility that the other Org will see the data of the other from the cached data? Or, is the cache objects tied to a specific organisation only?

**Comment by wizardist** [comment]
Hi @MCKLtech 

The toolkit assumes full ownership of the cache pool, and it is bound to the toolkit instance, i.e. not a static member. If you have two toolkit instances, each with a distinct cache pool instance, each pointing to different physical storage (e.g. different filesystem namespace or prefix), then you're safe.

In the code you've provided, it seems that the service container returns the same cache instance every time, so you probably need to change that.

**Comment by MCKLtech** [comment]
Thank you wizardist.

So, to double-check, all data is common to the cache pool unless I pass an org specific cache pool when setting up via createOnlineClient?

In terms of another approach to do this, is it possible to override the key functions of the cachePool to append say an org ID? 

The main reason for asking is that the system overall is very slow without a cache but we need to support, and separate, different orgs.

**Comment by wizardist** [comment]
@MCKLtech every cache store in Laravel that I know of allows specifying a prefix, or directory (for FileStore). Use that. [1](https://laravel.com/api/6.x/Illuminate/Cache/FileStore.html#method___construct) [2](https://laravel.com/api/6.x/Illuminate/Cache/RedisStore.html#method___construct) [3](https://laravel.com/api/6.x/Illuminate/Cache/DatabaseStore.html#method___construct)

Don't use the dependency injection, but create the pools manually: construct the store, make a repositry, then wrap with `IlluminatePsrCacheBridge`.

**Comment by MCKLtech** [comment]
Thank you @wizardist, that's a wonderful information and I appreciate the breakdown of the steps.

May I ask do you have an example of how this could be achieved in Laravel? I can see the rough outline via the FileStore API but I'm having trouble getting my code functional.
