### ISSUE TITLE
Unable to retrive a collection of results

### ISSUE THREAD

**Issue by stevewolfe555** [AlexaCRM/dynamics-webapi-toolkit#21]
**Describe the bug**
I am able to retrieve single entities when querying by ID or another field.
When querying with Retrieve Multiple I am getting a 0 result count in the list returned.

**To Reproduce**
Excuse formatting it didn't like the XML
$fetchXML = <<< FETCHXML
```
<fetch mapping="logical" count="10" paging-cookie="%s" page="%d">
  <entity name="account">
    <attribute name="name" />
    <attribute name="telephone1" />
    <attribute name="address1_city" />
    <attribute name="primarycontactid" />
    <attribute name="statecode" />
  </entity>
```
</fetch>
FETCHXML;

$page = 1;
$query = new \AlexaCRM\Xrm\Query\FetchExpression( sprintf( $fetchXML, '', $page ) );

$result = $client->RetrieveMultiple( $query );

**Comment by georged** [comment]
1. Fetchxml does not seem to have a closing tag `<\fetchxml>`
2. Try `<fetch mapping="logical" count="10">` first, i.e. without paging cookie or page

**Comment by stevewolfe555** [comment]
oh well done removing the  paging-cookie="%s" page="%d" fixed it.

**Comment by stevewolfe555** [comment]
Ah the paging doesnt want to work now

while ( $result->MoreRecords ) {
        $query->Query = sprintf( $fetchXML, htmlentities( $result->PagingCookie, ENT_COMPAT | ENT_XML1 ), ++$page );
        exit;
        $result = $client->RetrieveMultiple( $query );
        foreach ( $result->Entities as $account ) {
            echo $account['name'] .'<br>';
        }
    }

**Comment by stevewolfe555** [comment]
Ignore me, I've reverted the code and all working now. Must have been a D365 issue
