### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by stevewolfe555** [AlexaCRM/dynamics-webapi-toolkit#22]
**Describe the bug**
With the Fetch XML is it possible to pull in the relations?

**To Reproduce**
`
<entity name="account">
        <attribute name="name" />
        <attribute name="telephone1" />
        <attribute name="address1_city" />
        <attribute name="primarycontactid" />
        <attribute name="statecode" />
        <link-entity name="contact" from="contactid" to="primarycontactid" visible="false" link-type="outer" alias="accountprimarycontactidcontactcontactid">
      <attribute name="emailaddress1" />
    </entity>
`

**Comment by georged** [comment]
Absolutely, see [FetchXML documentation](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query). I'm not sure what's the bug you're trying to describe.
