### ISSUE TITLE
Unable to install via Composer

### ISSUE THREAD

**Issue by wpnetninjas** [AlexaCRM/dynamics-webapi-toolkit#26]
**Describe the bug**
Have tried to install via Composer however we are receiving an installation dependency error

> composer require alexacrm/dynamics-webapi-toolkit:dev-master

./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for alexacrm/dynamics-webapi-toolkit dev-master -> satisfiable by alexacrm/dynamics-webapi-toolkit[dev-master].
    - alexacrm/dynamics-webapi-toolkit dev-master requires alexacrm/strong-serializer dev-master -> satisfiable by alexacrm/strong-serializer[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by Stefaans** [comment]
I encountered the same error, and could fix it by modifying composer.json as follows:
`"minimum-stability": "dev",
"prefer-stable": true,`

**Comment by wpnetninjas** [comment]
Likewise, thank you for sharing, @Stefaans. It seems they might have updated composer.json now in the release also?

**Comment by sktnetwork** [comment]
My issue is similar. It gave following error:

Problem 1
    - Root composer.json requires alexacrm/dynamics-webapi-toolkit dev-master -> satisfiable by alexacrm/dynamics-webapi-toolkit[dev-master].
    - alexacrm/dynamics-webapi-toolkit dev-master requires alexacrm/strong-serializer ^2.0 -> found alexacrm/strong-serializer[2.0] but it conflicts with your root composer.json require (dev-master).

The solution was to manually edit the composer.json and change:
> "alexacrm/strong-serializer": "dev-master",
TO
> "alexacrm/strong-serializer": "^2.0",
