### ISSUE TITLE
Example about how to use OData helper

### ISSUE THREAD

**Issue by innovaitec** [AlexaCRM/dynamics-webapi-toolkit#29]
Hi, can you please provide an example of how to use the OData helper to manually query data? I am trying to get optionset names based on their integer values but I cannot figure out the correct way to perform a call.

Thanks for your time,
Xavier Villafuerte

**Comment by wizardist** [comment]
Hi @innovaitec 

Look at `MetadataRegistry` to see how it works with organization metadata via Web API.

You could also provide a sample OData query so that I could better understand what you're after here.

HTH

**Comment by innovaitec** [comment]
Hi, thanks for your quick response. What I am trying to achieve is to get the value labels for an specific local option set created for the contact entity. A query example is as follows:

https://yourcrm.crm.dynamics.com/api/data/v9.0/EntityDefinitions(LogicalName=’contact’)/Attributes/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$filter=LogicalName eq 'inn_myoptionset'&$expand=OptionSet

I am using the following article to understand the query:

https://carldesouza.com/getting-local-option-set-metadata-with-webapi-javascript/

Usually we use JS to perform this kind of operations but this time php is needed and your plugin is a great tool for this task. Thanks for your time.




Xavier Villafuerte
Consultor Senior
xavier@innovait.ec



________________________________

**Comment by wizardist** [comment]
@innovaitec 

That's pretty much what `MetadataRegistry` does, only it retrieves all attribute metadata.

Your query would translate to smth like this

``` php
$this->client->getList( "EntityDefinitions(LogicalName='contact')/Attributes/Microsoft.Dynamics.CRM.PicklistAttributeMetadata", [
  'Select' => 'LogicalName',
  'Filter' => "LogicalName eq 'inn_myoptionset'",
  'Expand' => 'OptionSet',
] );
```

Thanks

**Comment by innovaitec** [comment]
Thanks, I managed to use MetadataRegistry to get the information I needed.




Xavier Villafuerte


________________________________
