### ISSUE TITLE
Could not find a version of package alexacrm/dynamics-webapi-toolkit matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

### ISSUE THREAD

**Issue by djnotes** [AlexaCRM/dynamics-webapi-toolkit#3]
After failing to use php-crm-toolkit to create a contact in Dynamics at http://0.0.0.0:8088/mysite/api/data/v8.2 from PHP code, I am trying to use dynamics-webapi-toolkit. When I require it with composer, I get the following error:   

```
  composer require alexacrm/dynamics-webapi-toolkit
Cannot load Xdebug - it was already loaded

                                                                                                                                                    
  [InvalidArgumentException]                                                                                                                        
  Could not find a version of package alexacrm/dynamics-webapi-toolkit matching your minimum-stability (stable). Require it with an explicit versi  
  on constraint allowing its desired stability.                                                                                                     
                                                 
```
I tried solving this by adding --prefer-stable to `require` but, it didn't help either resulting in the same error.

**Comment by wizardist** [comment]
Hi @djnotes

You need to add `"minimum-stability": "dev"` to your `composer.json` in order to install the library. The library hasn't been tagged so far as there's no stable version at the moment.

HTH

P.S. What is your Dynamics 365 deployment type? IFD or On-Premises?

**Comment by djnotes** [comment]
@wizardist it is Dynamics 365 on-premises.

**Comment by sulaimaan46** [comment]
> Hi @djnotes
> 
> You need to add `"minimum-stability": "dev"` to your `composer.json` in order to install the library. The library hasn't been tagged so far as there's no stable version at the moment.



>I am tried this method but still is not working .any other way to solve this issues?
