### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by koenhoeijmakers** [AlexaCRM/dynamics-webapi-toolkit#33]
It would be pretty nice if the package would have releases.
The current change that requires `php7.4` forced us to update our project.
I'm all for keeping projects up to date, but we would have rather picked another time to update our project.

Having actual releases that we can rely on would really help with this as `dev-master` just doesn't cut it.

**Comment by wizardist** [comment]
Hi @koenhoeijmakers 

Sorry to hear this happen. We haven't started tagging because the library is not quite ready, and we can't give a compatibility promise yet.

Perhaps you should have set a hard commit hash constraint to keep the library from updating. Another thing to notice is that a sweeping `composer update` is not necessarily a healthy thing.

**Comment by mremi** [comment]
Hi,

I have the same issue with the required version of php, maybe a release 0.0.1 from the commit ebd3bc439333bbc0a0bdf9201bfeff639b3668bc is a possible option?

**Comment by AliensYann** [comment]
First of all, thank you for creating and maintaining this package!

Could you please make a release of #ebd3bc4 as mremi mentioned? Our application is currently dependend on your package, and upgrading it to PHP 7.4 would be an enormous amount of work (weeks).

**Comment by karlmiles** [comment]
I've had to update my composer.json to use `dev-master#ebd3bc4`, not because of PHP 7.4 exactly (my project's already using PHP 7.4) but, I get errors as a result of other changes in subsequent commit.

**Comment by wizardist** [comment]
Hi guys

Thanks for pointing that out. Please specify `^2.0.1` if you're developing for PHP 7.4 and beyond. Otherwise please stick to `^1.0`.

**Comment by AliensYann** [comment]
Hi Wizardist,

Thank you for implementing this so fast!

**Comment by mremi** [comment]
Thanks a lot!
