### ISSUE TITLE
Retrieve multiple records with SQL JOIN

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#34]
Hi,

Is it a possibility to retrieve multiple records of associated entities ? (In SQL we are using JOINS).

Thanks and regards.

**Comment by georged** [comment]
Hi @grunam 

to retrieve related records you can use either `$expand` clause in [web api](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-related-entities-query) or build [fetchxml](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query) and [execute it](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries) using either saved or custom queries.

HTH
George
