### ISSUE TITLE
Retrieve PickList  with dynamics-webapi-toolkit

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#37]
Hi,

How can I retrieve a PickList type (label and value) via dynamics webapi toolkit ?

Thanks and regards.

**Comment by wizardist** [comment]
Hi @grunam 

If you want to retrieve the current label of the field, then the easiest option is to use one from `FormattedValues`:

```php
echo $account->FormattedValues['industrycode'] ?? '';
```

If however you want to retrieve all values and labels of an entity attribute, you need to access entity metadata:

```php
$options = ( new MetadataRegistry( $client ) )->getDefinition( 'account' )->Attributes['industrycode']->OptionSet->Options;
foreach ( $options as $option ) {
  echo "Option #{$option->Value}, Label '{$option->Label->UserLocalizedLabel->Label}'";
}
```

The organization metadata API is the same as XRM. That includes handling of labels -- see `$option->Label->LocalizedLabels` for a collection of labels in every installed language. One difference there -- it is mapped by LCID, so you can access the LocalizedLabel directly, e.g. `$option->Label->LocalizedLabels[1033]->Label`.

Thanks
