### ISSUE TITLE
Upload an attachment In MS Dynamics

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#38]
Hi,

Are there a way to upload an attachment in MS Dynamics with dynamics-webapi-toolkit ?

Thanks and Regards

**Comment by georged** [comment]
@grunam 

adding an attachment is no different from creating any new record. 

1. Upload attachment using whatever file control you have
2. On the server, create `annotation` record and assign 64-bit encoded file content to the `documentbody` attribute.

See [documentation](https://docs.microsoft.com/powerapps/developer/common-data-service/reference/entities/annotation) for more details
