### ISSUE TITLE
Update birthdate 

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#40]
Hi,

I try to update birthdate with code below without any success.

$dateTime = new DateTime('1979-01-16 00:00:00');
$dateTime = $dateTime->getTimestamp();
$contact['birthdate'] = $dateTime;

Could you  help me please ?

Thanks and regards

**Comment by georged** [comment]
@grunam 
as per OData specs, dates are in ISO 8601:

`$contact['birthdate'] = '2000-12-09';
$contact['overriddencreatedon']='2000-12-09T02:03:04Z';`
