### ISSUE TITLE
Remove Dynamics 365 references

### ISSUE THREAD

**Issue by georged** [AlexaCRM/dynamics-webapi-toolkit#43]
The toolkit is agnostic and does not have any dependencies on Dynamics 365. All error messages should refer to Common Data Service instead.

Note: potentially CDS will change its name as well (due to the project Oakdale developments) but probability is low. Regardless, name of the product/underlying technology should be an easy to change constant.

**Comment by rlemmen** [comment]
Unlikely and yet it did change names. Again. And again :)

**Comment by georged** [comment]
😩😩😩
