### ISSUE TITLE
Is dynamics-webapi-toolkit comptible with Microsoft Dynamics NAV ?

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#44]
Hi,

Is dynamics-webapi-toolkit comptible with Microsoft Dynamics NAV (instead of Microsoft 365) ?  

Thanks and regards.

**Comment by georged** [comment]
@grunam 

this toolkit only supports Common Data Service Web API, Dynamics NAV is not supported

Thanks
George
