### ISSUE TITLE
Manage errors for CRUD queries

### ISSUE THREAD

**Issue by grunam** [AlexaCRM/dynamics-webapi-toolkit#45]
Hi,

How can I manage errors for CRUD queries with the returned value (knowing that I don't know the returned value in the case of error) ?
With PHP we can use try { } catch (customException $e) { echo $e->errorMessage();}, but with dynamics-webapi-toolkit what is the good way ?

Thanks and regards.

**Comment by georged** [comment]
@grunam 

retrieve returns null if record is not found. In case of any error, an exception is thrown. 

Thanks
