### ISSUE TITLE
Syntax error in tutorial

### ISSUE THREAD

**Issue by williamrenfrew** [AlexaCRM/dynamics-webapi-toolkit#47]
**Describe the bug**
A closing bracket `)` is missing from the *Retrieve a record* section of the tutorial wiki page.
 
**To Reproduce**
1. Navigate to [Retrieve a record](https://github.com/AlexaCRM/dynamics-webapi-toolkit/wiki/Tutorial#retrieve-a-record) in the tutorial
2. Use the code

**Expected behavior**
Code example should be updated from
```php
$retrievedContact = $client->Retrieve( 'contact', $contactId, new \AlexaCRM\Xrm\ColumnSet( [ 'fullname', 'emailaddress1' ] );
```
to
```php
$retrievedContact = $client->Retrieve( 'contact', $contactId, new \AlexaCRM\Xrm\ColumnSet( [ 'fullname', 'emailaddress1' ] ) );
```

**Comment by wizardist** [comment]
Thanks!
