### ISSUE TITLE
PHP upload - "The file attribute value sent ... is not a valid Guid"

### ISSUE THREAD

**Issue by marineadz** [AlexaCRM/dynamics-webapi-toolkit#48]
Successfully updated an image field type in Dataverse using the toolkit with 
`(
'cds_field_name' => base64_encode('/path/to/file.ext'))
)`
(file is checked for mime, etc. first, but that gives you the basic version)

Tried the same with a file field type (testing with a .png file) and get the error "The file attribute value sent ... is not a valid Guid".

Are file submissions supported, or have I missed something else?

**Comment by georged** [comment]
@marineadz would you mind sharing the code? It's not possible to tell anything from the fragment.
