### ISSUE TITLE
403 code while fetching record

### ISSUE THREAD

**Issue by CaptainCannabis** [AlexaCRM/dynamics-webapi-toolkit#49]
Not realy a bug report.

_I am getting the Message: Metadata request returned a 403 code while fetching record. Can you please suggest what am i missing ?
I am connecting with crm like below with my dynamic credentials -_

I did everything stated here:

https://docs.microsoft.com/de-DE/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory

I guess its a problem with my azure/dynamics config. If i try to connect by using [fetchxmlbuilder](https://fetchxmlbuilder.com/) i can choose the method "client id / secret". If i put my dynamics organization url in and the app-id & key it fails and tries to switch to outh. If i enter my credentials (email and password) oauth login works and i can fetch data from the api. 

I got a developer account from ms developer program, sales Professional and all that stuff.

What could be wrong in my setup?

Its hard to get any support by official contacts so sorry for spaming in your issues!

**Comment by georged** [comment]
If you can't connect with client id/secret from xrmtoolbox, that's a good indication that it's a configuration issue.

Couple questions that I asked the other poster. 

- do you have an app user set up in the instance
- does this user have the role assigned

Thanks

**Comment by CaptainCannabis** [comment]
What exactly do you mean with "app user". I got some active directory users. For those i added licenses for dynamics. These users got roles like "Sales Professional Person" or "System Administrator". When evertything regarding sales professional worked in browser i set up an application in azure. Generated a token for that application and set the permissions for that application like mentioned everywhere.

That way i get an url, application and token.T thought thats the three things i need for authentication. If i log in with xrmtoolbox and choose "client id/ key" there is no need for a user. A user (with mail an password) would be used by logging in via oauth, or am i wrong?

**Comment by georged** [comment]
@CaptainCannabis 

this is documented as part of [Getting Started](https://docs.alexacrm.com/integration-cds/getting-started/#get-credentials):

> Next step is to create an application user in CRM. Go to the Admin center, navigate to your environment’s Settings / Users. Switch to the Application Users view, hit New, switch to the “Application User” form, as can be seen here. Fill in the Application ID which you saved before, as well as Full Name and Primary Email fields, then save the user. Associate the user with relevant security roles, for example “System Administrator” and “Delegate”. Feel free to create custom security roles which suit your use case best.

You can follow [step by step instructions](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-single-tenant-server-server-authentication#application-user-creation) in the offical Microsoft docs.
