### ISSUE TITLE
Metadata request returned a 403 code

### ISSUE THREAD

**Issue by amanjlucid** [AlexaCRM/dynamics-webapi-toolkit#50]
Getting metadata request returned a 403 code while connecting with dynamic crm. I have tried everything but still getting the same error. I have a user in dataverse too. Do i need to create another user with roles. I have very little knowledge about crm. Could you please suggest what am i doing wrong ?

**Comment by georged** [comment]
I suspect you haven't created an application user (which is not the same as interactive user). Please read #49 thread and make sure you followed all the steps discussed.

**Comment by amanjlucid** [comment]
You are right, i haven't given the permission to the application user now it is resolved. Thanks @georged
