### ISSUE TITLE
Setting a GuID attribute

### ISSUE THREAD

**Issue by supporto-wifiproject** [AlexaCRM/dynamics-webapi-toolkit#51]
I have an entity which has some attributes of GuID Type. How can assign a value to this attributes? If Iuse this syntax:
`$entity['attribute'] = "GuID string'`
the attributes remains empty.
Could you help me, please?

**Comment by georged** [comment]
@supporto-wifiproject there is no attribute of "GuID Type" in Dataverse. What exactly are you trying to set? A lookup value?

**Comment by supporto-wifiproject** [comment]
I have an entity which a filed who contain the value of the ID of another entity but without relationship. Finally, I managed to set the value with
`new \AlexaCRM\Xrm\EntityReference('other entity', $myValue);`
Thanks

**Comment by georged** [comment]
@supporto-wifiproject 
It's a lookup type. Not that there is no relationship - you probably just don't know the name of it. Using entity reference is one way to set the value, the other is to use associate method.
