### ISSUE TITLE
While updating entity I am getting update request failed

### ISSUE THREAD

**Issue by amanjlucid** [AlexaCRM/dynamics-webapi-toolkit#70]
{"status":false,"message":"Update request failed: Client error: `PATCH  resulted in a `405 Method Not Allowed` response with the following message: `The requested resource does not support http method 'PATCH'.`"}

Could you please provide me a solution or reason why i am getting this error and the related entity is getting updated when using dotnet.

**Comment by georged** [comment]
@amanjlucid, can you show your code?

**Comment by amanjlucid** [comment]
Thanks for the reply, I was not passing the id for entity, I have resolved this, Thanks
