### ISSUE TITLE
Deprecated Error Message

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/dynamics-webapi-toolkit#81]
I am getting the error below:

![image](https://user-images.githubusercontent.com/10854571/185420550-8842540a-7df0-4aa3-a07b-62d2de393b74.png)

Please, could you help me to solve the issue, or, hide the message?

**Php version:** 8.1.5
I changed already the php.ini file but the deprecated error message is still displayed.

![image](https://user-images.githubusercontent.com/10854571/185421885-f29f2d16-1ad1-4807-ad8c-17db6856abf9.png)

![image](https://user-images.githubusercontent.com/10854571/185421737-6155b37c-e18d-482d-9ad1-595bc636d850.png)

![image](https://user-images.githubusercontent.com/10854571/185422038-373cceb3-9e5e-406f-be43-a7cf97d9594f.png)

Please, could you help me?

**Comment by dantedantas** [comment]
Please, could someone help me with this issue?

**Comment by georged** [comment]
@dantedantas
 
the warnings will be fixed in due course. It looks like an environmental issue because disabling deprecated and strict should be sufficient. If you can't resolve it by supressing then I'd recommend downgrading PHP version as we are unable to provide support for specific environments.

**Comment by dantedantas** [comment]
Thank you Georg.
