### ISSUE TITLE
Associate requests fail

### ISSUE THREAD

**Issue by agentmarine** [AlexaCRM/dynamics-webapi-toolkit#9]
**Describe the bug**
when trying to associate entities, the URL outputs correctly but is appended with $ref which is not valid on the segment after the navProperty

**To Reproduce**
just run $client->associate

**Expected behavior**
Entities to be associated.

**Additional context**
It also looks like disassociate might suffer from the same issue, but i've not tested it at this point.

**Recomended change**
>From
   `$url  = sprintf( '%s%s(%s)/%s$ref', $this->settings->getEndpointURI(), $fromEntityCollection, $fromEntityId, $navProperty );`
>to
`$url  = sprintf( '%s%s(%s)/%s', $this->settings->getEndpointURI(), $fromEntityCollection, $fromEntityId, $navProperty );`

**Comment by georged** [comment]
@agentmarine 
can you give us a code snippet that calls the association and causes the error?

**Comment by agentmarine** [comment]
Hi @georged sure here you go,

```
public function associateApplication($applicationId, $contactId)
    {
        $this->client->Associate(
            'contact',
            $contactId,
            new \AlexaCRM\Xrm\Relationship( 'asc_contact_asc_application' ),
            [
                new \AlexaCRM\Xrm\EntityReference( 'asc_application', $applicationId ),
            ]
        );
    }
```

**Comment by georged** [comment]
@agentmarine 
and the error you're getting is? (trying to understand what's going on because according to https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api, you do have to have $href on url)

**Comment by agentmarine** [comment]
> App\Services\DynamicsHandler {#3030}>>> $dh->associateApplication('07dbdf22-e186-e911-a99c-00224800c5e8', '0dcd24c2-dc86-e911-a99c-00224800c5e8');AlexaCRM/WebAPI/OrganizationException with message 'Associate request failed: Client error: `POST https://xxxxxxxxxxxxxxxxx.crm11.dynamics.com/api/data/v9.0/contacts(0dcd24c2-dc86-e911-a99c-00224800c5e8)/asc_contact_asc_application$ref` resulted in a `404 Not Found` response with the following message: `Resource not found for the segment 'asc_contact_asc_application$ref'`

**Comment by agentmarine** [comment]
I suspect it might be a misstype in the documentation, if you look at the lower example [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api#associate-entities-on-update-using-single-valued-navigation-property), it shows the requests without the $ref

I've also been using the client locally modified to not have the $ref and its been working.

**Comment by wizardist** [comment]
@agentmarine not really, those are two different requests.

I wonder why there is no forward slash before `$ref`. It must be `/contacts(0dcd24c2-dc86-e911-a99c-00224800c5e8)/asc_contact_asc_application/$ref`. The slash is in the toolkit `OData/Client.php:466`. Are you using the latest commit?

**Comment by georged** [comment]
@agentmarine 

as @wizardist mentioned, those are different requests. You're referring to the single-valued nav property which is updated by PATCH. You're calling a collection method, however, which is a POST with `$ref`, as documented. It looks like the error is due to a missing slash.

**Comment by agentmarine** [comment]
does look to be that, way, havent updated for a while, so i just did it and its pulled the latest versions which seems to be working. Sorry to waste your time with this :)
