### ISSUE TITLE
Update composer.json to allow psr/cache 3.0

### ISSUE THREAD

**Issue by fabianderijk** [AlexaCRM/dynamics-webapi-toolkit#98]
I'm using Drupal 10.1. As per https://github.com/AlexaCRM/dynamics-webapi-toolkit/pull/97 the dependency to psr/log was updated to the correct version, however Drupal 10.1 also requires psr/cache ~3.0.0

Can this be added in the composer.json as well? I'll create a PR for this.

**Comment by fabianderijk** [comment]
PR has been created in https://github.com/AlexaCRM/dynamics-webapi-toolkit/pull/99

**Comment by mrudov** [comment]
Fixed in v4 branch. Refer README.md for details.
